### ISSUE TITLE
Add Microsoft Teams Rooms Managed Services portal

### ISSUE THREAD

**Issue by DJHowellCA** [adamfowlerit/msportals.xyz#59]
Add the Microsoft Teams Rooms Managed Services portal, which is provided by purchasing Teams Room Premium licenses.

**Name:** Microsoft Teams Rooms Managed Services
**URL:** https://portal.rooms.microsoft.com/

References:
- https://techcommunity.microsoft.com/t5/microsoft-teams-blog/introducing-the-new-microsoft-teams-rooms-premium/ba-p/1527686
- https://portal.rooms.microsoft.com/docs/Managed%20Meeting%20Rooms%20Portal%20Guide%20June%202020.pdf
- https://content.cloudguides.com/en-us/guides/Get%20to%20know%20the%20Managed%20Meeting%20Rooms%20portal

**Comment by PsychoData** [comment]
Adding to this - 
This is tied to Teams Rooms Premium/ Managed Teams Rooms - list price $50
https://docs.microsoft.com/en-us/microsoftteams/rooms/microsoft-teams-rooms-premium

versus Teams Room Standard - list price $15 - that you would access from https://admin.teams.microsoft.com/ 
https://docs.microsoft.com/en-us/MicrosoftTeams/rooms/rooms-manage

[a blog](https://tomtalks.blog/2020/07/understanding-microsoft-teams-rooms-standard-vs-premium/) I found outlining the differences. 

Seems like the Admin/home page makes the most sense - but I am loath to add it to the "Microsoft 365 Admin Portals" section though since it is such a specialized SKU - at least right now. 

Does the [Other useful portals](https://msportals.xyz/?search=#other-useful-microsoft-portals) section seem good?

**Comment by DJHowellCA** [comment]
Premium does not replace Teams Admin Center, rather it compliments it. There is more telemetry, more control around updates, alerting, and the dedicated Microsoft support team to investigate and resolve issues.

I personally think it belongs in Microsoft 365 Admin Portals because it is for an M365 service. While its niche right now, it is going to grow in popularity. And there are already other links in that category such as Partner Center and Microsoft Store for Education that only serve certain verticals or license types.

But regardless, I'd just like it listed. :-)

**Comment by adamfowlerit** [comment]
Both valid points - but I'm leaning towards the Microsoft 365 Admin Portals section because I don't want to have to make judgement calls as to how important a portal is or not; it should fit in a category, or go in the Other useful portals section if it really doesn't fit. Other useful portals was a grey area for not really admin portals, but ones admins might still use. This seems more of a true admin portal.

**Comment by DJHowellCA** [comment]
IMO Remote Connectivity Analyzer is the one that doesn't belong in M365 Admin Portals. It is not specific to M365 and is a test tool not an admin portal.

**Comment by adamfowlerit** [comment]
Agree, have moved Remote Conectivity Analyzer to 'other'

**Comment by adamfowlerit** [comment]
I'll do this change, we can always change again later or even create a separate 'Managed Services' section if more turn up, or open to other different ways we categorize the URLs.
